# Generated by Django 4.2.7 on 2023-11-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoFuerza',
            fields=[
                ('idEdoFuerza', models.AutoField(primary_key=True, serialize=False)),
                ('oficinaR', models.CharField(max_length=50)),
                ('numPunto', models.IntegerField()),
                ('nomPuntoRevision', models.CharField(max_length=100)),
                ('tipoP', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=300)),
                ('coordenadasTexto', models.CharField(max_length=300)),
                ('latitud', models.FloatField(default=0.0)),
                ('longitud', models.FloatField(default=0.0)),
                ('personalINM', models.IntegerField()),
                ('personalSEDENA', models.IntegerField()),
                ('personalMarina', models.IntegerField()),
                ('personalGuardiaN', models.IntegerField()),
                ('personalOTROS', models.IntegerField()),
                ('vehiculos', models.IntegerField()),
                ('seccion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('idMunicipio', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=250)),
                ('estadoAbr', models.CharField(max_length=50)),
                ('nomMunicipio', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('idPais', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pais', models.CharField(max_length=250)),
                ('iso3', models.CharField(max_length=3, null=True)),
            ],
        ),
    ]
